fsc_cmfw1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('showapp/', include("showapp.urls")),
]

showapp/urls.py
from django.urls import path
from showapp import views

app_name='showapp'

urlpatterns =[
    path('index/',views.index,name='index'),
    path('login/',views.login,name='login'),
    path('get_code/',views.get_code,name='get_code'),
    path('check_user/',views.check_user,name='check_user'),
    path('add_banner/',views.add_banner,name='add_banner'),
    path('loadbanner/',views.loadbanner,name='loadbanner'),
    path('del_banner/',views.del_banner,name='del_banner'),
    path('loadusers/',views.loadusers,name='loadusers'),
    path('add_user/',views.add_user,name='add_user'),
    path('del_user/',views.del_user,name='del_user'),
    path('get_maplist/',views.get_maplist,name='get_maplist'),
    path('get_initlist/',views.get_initlist,name='get_initlist'),
]

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>主页</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'bs/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bs/css/back.css' %}">
    <script type="text/javascript" src="/static/bs/js/jquery-2.2.1.min.js/"></script>
    <link rel="stylesheet" href="{% static 'jqgrid/css/trirand/ui.jqgrid-bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'jqgrid/css/jquery-ui.css' %}">
    <script src="{% static 'bs/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'jqgrid/js/trirand/src/jquery.jqGrid.js' %}"></script>
    <script src="{% static 'jqgrid/js/trirand/i18n/grid.locale-cn.js' %}"></script>
    <script src="{% static 'bs/js/ajaxfileupload.js' %}"></script>

    <script src="{% static 'echarts/js/echarts.min.js' %}"></script>
    <script src="{% static 'echarts/js/echarts.min.js' %}"></script>
    <script src="{% static 'echarts/js/china.js' %}"></script>

</head>
<body>
<div class="container-fluid">
{#导航条#}
    <nav class="navbar navbar-default" style="background-color: white">
        <div class="container-fluid">
{#            左边文字#}
            <div class="navbar-header">
                <a class="navbar-brand" href="#">持明法洲管理系统</a>
            </div>
{#            右边退出#}
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">欢迎：{{ uname }}</a></li>
                    <li><a href="{% url 'showapp:login' %}">退出登录 <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span></a></li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
{#    中部---左侧手风琴、右侧巨幕、轮播图#}
    <div class="row">
{#        手风琴#}
        <div class="col-md-2">
            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
              <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingOne">
                  <h4 class="panel-title">
                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                      用户管理
                    </a>
                  </h4>
                </div>
                <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                  <div class="panel-body">
                     <ul class="nav nav-pills nav-stacked">
                        <li><a href="javascript:$('#centerLayout').load('{% static 'static_html/users.html' %}')" style="font-weight: bold">用户们</a></li>
                        <li><a href="javascript:$('#centerLayout').load('{% static 'static_html/echart_map.html' %}')" style="font-weight: bold">用户分布图</a></li>
                        <li><a href="javascript:$('#centerLayout').load('{% static 'static_html/echart_init.html' %}')" style="font-weight: bold">用户注册图</a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingTwo">
                  <h4 class="panel-title">
                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                      文章管理
                    </a>
                  </h4>
                </div>
                <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                  <div class="panel-body">
                      <ul class="nav nav-pills nav-stacked">
                        <li><a href="javascript:" style="font-weight: bold">文章们</a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingThree">
                  <h4 class="panel-title">
                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                      专辑管理
                    </a>
                  </h4>
                </div>
                <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                  <div class="panel-body">
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="javascript:" style="font-weight: bold">专辑们</a></li>
                    </ul>
                  </div>
                </div>
              </div>
                <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingFour">
                  <h4 class="panel-title">
                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseThree">
                      轮播图管理
                    </a>
                  </h4>
                </div>
                <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
                  <div class="panel-body">
                  <!--通过load方法加载轮播图管理的页面-->
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="javascript:$('#centerLayout').load('{% static 'static_html/banner.html' %}')" style="font-weight: bold">轮播图们</a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
        </div>
{#        巨幕、轮播图#}
        <div class="col-md-10" id="centerLayout">
{#            巨幕#}
            <div class="row">
                <div class="jumbotron">
                    <h2 style="color:gray">欢迎来到持明法洲后台管理系统</h2>
                </div>
            </div>
{#            轮播图#}
            <div class="row">
                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                    <!-- Indicators -->
                    <ol class="carousel-indicators">
                        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                    </ol>

                    <!-- Wrapper for slides -->
                    <div class="carousel-inner" role="listbox">
                        <div class="item active">
                            <img src="{% static 'carouse/544cfd607318138adda68e01d19099a.jpg' %}" alt="...">
                            <div class="carousel-caption">
                                1111111111
                            </div>
                        </div>
                        <div class="item">
                            <img src="{% static 'carouse/1.jpg' %}" alt="...">
                            <div class="carousel-caption">
                                222222222
                            </div>
                        </div>
                        <div class="item">
                            <img src="{% static 'carouse/2.jpg' %}" alt="...">
                            <div class="carousel-caption">
                                333333333
                            </div>
                        </div>
{#                        轮播图#}
                    </div>

                    <!-- Controls -->
                    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div> <!--轮播图-->
        </div> <!--右侧 巨幕、轮播图-->
    </div>
{#    固定底部导航栏#}
    <div class="panel-footer">
        <div class="panel-title">
            <h5 style="text-align: center">@百知教育 baizhi@zparkhr.com.cn</h5>
        </div>
    </div>
</div>
<!--模态框-->
<div class="modal fade" id="myModal11" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content" style="width:750px">
            <!--模态框标题-->
            <div class="modal-header">
                <!-- 用来关闭模态框的属性:data-dismiss="modal"-->
                <button type="button" class="close" data-dismiss="modal"><span>&times;</span></button>
                <h4 class="modal-title">编辑用户信息</h4>
            </div>
            <!--模态框内容体-->
            <div class="modal-body">
                <form action=" " class="form-horizontal" id="addArticleFrom">
                    <div class="form-group">
                        <label class="col-sm-1 control-label">标题</label>
                        <div class="col-sm-5">
                            <input type="text" name="title" id="title" placeholder="请输入标题" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">状态</label>
                        <div class="col-sm-5">
                            <select class="form-control" name="status" id="status">
                                <option value="1">展示</option>
                                <option value="2">不展示</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-12">
                            <textarea id="editor_id" name="content" style="width:700px;height:300px;">

                            </textarea>
                        </div>
                    </div>
                    <input id="addInsertImg" name="insertImg" hidden>
                </form>
            </div>
            <!--模态页脚-->
            <div class="modal-footer" id="modal_footer">

            </div>
        </div>
    </div>
</div>


</body>
</html>

templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
     <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>持明法周后台管理系统</title>
    <link rel="stylesheet" href="{% static 'bs/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bs/css/ui.jqgrid-bootstrap.css' %}">
    <script src="{% static 'bs/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'bs/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'jqgrid/js/i18n/grid.locale-cn.js' %}"></script>
    <script src="{% static 'jqgrid/js/jquery.jqGrid.min.js' %}"></script>

</head>
<body>
<div class="container">
{#    标题#}
    <div class="page-header">
        <h2 class="text-center" id="title">持明法周管后台理系统登录页面</h2>
    </div>
{#    表单#}
    <script type="text/javascript">
    // 发送按钮倒计时代码
        var countdown = 60;
        function settime(obj) {
            if (countdown == 0) {
                obj.removeAttribute("disabled");
                obj.value = "免费获取验证码";
                countdown = 60;
                return;
            } else {
                obj.setAttribute("disabled", true);
                obj.value = "重新发送(" + countdown + ")";
                countdown--;
            }
            setTimeout(function () {
                settime(obj)
                }
                , 1000)
        }

        $(function () {
            var flag1 = false;
            //验证手机号
            $('#mobile').blur(function () {
                var username = $('#mobile').val();
                var phonereg = /^1([38][0-9]|4[579]|5[0-3,5-9]|6[6]|7[0135678]|9[89])\d{8}$/; // 判断手机号是否合法
                if (username.trim() === '') {
                    flag1 = false;
                    $('#pid').text('手机号不能为空！').css('color','red');
                } else if (phonereg.test(username)) {
                    flag1 = true
                    $('#pid').text('OK！').css('color','green')
                } else {
                    flag1 = false;
                    $('#pid').text('该手机号不合法！').css('color','red')
                }

            });

            // 点击获取验证码， 向后台发送请求验证码
            $('#forcode').click(function () {
                // 向后台发送ajax请求获取验证码
                $.ajax({
                    url: "{% url 'showapp:get_code' %}",
                    type: "POST",
                    data: {mobile: $("#mobile").val()},       // 将手机号参数传至后台
                    success: function (data) {
                        console.log(data)
                        if (data=='ok'){
                            alert('获取验证码成功')
                        }else if (data=='error') {
                            alert('60秒内已经获取过，稍后请重试')
                        }else {
                            alert('what?')
                        }
                    }
                });

            });

           // 登录按钮
            $('#loginButtonId').click(function () {
                var code_input = $('#basic-url').val();
                var mobile = $('#mobile').val();
                var uname = $('#uname').val();
                 if (code_input.trim() === '') {
                     $('#pid1').text('验证码不能为空！').css('color','red');
                 } else {
                    if (flag1 === true) {
                        $.ajax({
                            type: 'post',
                            url: '{% url 'showapp:check_user' %}',
                            data: {code_input: code_input,mobile:mobile,uname:uname},
                            success: function (msg) {
                                if(msg==='ok'){
                                    location.href='/showapp/index?uname='+mobile
                                }else{
                                    $('#pid1').text('手机号或验证码错误！').css('color','red');
                                }
                            }
                        })
                    }else {
                         $('#pid1').text('请填写手机号或手机号格式不正确！').css('color','red');
                    }
                }
            });



        });
    </script>
    <!--手机号码输入框代码-->
    <div class="container">
        <div class="col-md-offset-3 col-md-6">
            <div class="form-group">
                <form id="loginForm" role="form" action="" method="post" class="form-horizontal">

                    <div class="form-group">
                        <label for="mobile" class="">手机号码:</label>
                        <div class="input-group">
                            <input type="text" class="form-control" required id="mobile" name="mobile" placeholder="手机号码">
                            <span class="input-group-btn">
                                <input type="button" id="forcode" onclick="settime(this)" value="免费获取验证码" class="btn btn-success">
                            </span>
                        </div>
                        <span id="msgDiv"></span>
                        <p class="help-block" id="pid">请填写绑定手机号</p>
                    </div>
                    <div class="form-group">
                        <label for="uname" class="">用户名</label>
                        <input type="text" class="form-control" id="uname" minlength="5" name="name" required>
                    </div>
                    <div class="form-group">
                        <label for="basic-url" class="">验证码：</label>
                        <input type="text" class="form-control" id="basic-url" required name="code">
                        <p class="help-block" id="pid1"></p>
                    </div>
                    <div class="input-group">
                        <input class="btn btn-success" type="button" id="loginButtonId" value="登录">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
</body>
</html>